# Generated by Django 5.1.6 on 2025-03-08 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compartment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('number_of_medicines', models.IntegerField()),
                ('to_be_repeated', models.BooleanField(default=False)),
                ('orario_medicina', models.TimeField(blank=True, null=True)),
                ('orario_mattina', models.TimeField(blank=True, null=True)),
                ('orario_pomeriggio', models.TimeField(blank=True, null=True)),
                ('orario_sera', models.TimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compartment2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('number_of_medicines', models.IntegerField()),
                ('to_be_repeated', models.BooleanField(default=False)),
                ('orario_medicina', models.TimeField(blank=True, null=True)),
                ('orario_mattina', models.TimeField(blank=True, null=True)),
                ('orario_pomeriggio', models.TimeField(blank=True, null=True)),
                ('orario_sera', models.TimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compartment3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('number_of_medicines', models.IntegerField()),
                ('to_be_repeated', models.BooleanField(default=False)),
                ('orario_medicina', models.TimeField(blank=True, null=True)),
                ('orario_mattina', models.TimeField(blank=True, null=True)),
                ('orario_pomeriggio', models.TimeField(blank=True, null=True)),
                ('orario_sera', models.TimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompartmentIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartment_id', models.PositiveIntegerField()),
                ('intake_time', models.TimeField()),
                ('taken', models.BooleanField(default=False)),
                ('taken_time', models.DateTimeField(blank=True, null=True)),
                ('compartment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
