# Generated by Django 5.1.6 on 2025-03-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compatment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_Name', models.CharField(max_length=200)),
                ('number_of_medicines', models.IntegerField()),
                ('to_be_repeated', models.BooleanField()),
                ('orario_medicina', models.TimeField()),
                ('orario_mattina', models.TimeField()),
                ('orario_pomeriggio', models.TimeField()),
                ('orario_sera', models.TimeField()),
            ],
        ),
    ]
