# Generated by Django 5.1.6 on 2025-03-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compartmentintake',
            name='intake_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
