# Generated by Django 5.1.6 on 2025-03-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_compatment1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compatment1',
            new_name='Compartment1',
        ),
    ]
