# Generated by Django 5.1.6 on 2025-03-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_rename_compatment1_compartment1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compartment1',
            name='orario_mattina',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='compartment1',
            name='orario_medicina',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='compartment1',
            name='orario_pomeriggio',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='compartment1',
            name='orario_sera',
            field=models.TimeField(blank=True),
        ),
    ]
