# Generated by Django 5.1.6 on 2025-03-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_compartment1_orario_mattina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compartment1',
            name='to_be_repeated',
            field=models.BooleanField(blank=True),
        ),
    ]
