# Generated by Django 5.1.6 on 2025-03-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_compartment1_to_be_repeated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compartment1',
            old_name='medicine_Name',
            new_name='medicine_name',
        ),
        migrations.AlterField(
            model_name='compartment1',
            name='orario_mattina',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compartment1',
            name='orario_medicina',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compartment1',
            name='orario_pomeriggio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compartment1',
            name='orario_sera',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compartment1',
            name='to_be_repeated',
            field=models.BooleanField(default=False),
        ),
    ]
