# Generated by Django 5.1.6 on 2025-03-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_rename_medicine_name_compartment1_medicine_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compartment1',
            name='taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compartment1',
            name='taken_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
