# Generated by Django 5.1.6 on 2025-03-08 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_compartmenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compartment1',
            name='taken',
        ),
        migrations.RemoveField(
            model_name='compartment1',
            name='taken_time',
        ),
        migrations.CreateModel(
            name='CompartmentIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_time', models.TimeField()),
                ('taken', models.BooleanField(default=False)),
                ('taken_time', models.DateTimeField(blank=True, null=True)),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='myapi.compartment1')),
            ],
        ),
        migrations.DeleteModel(
            name='CompartmentHistory',
        ),
    ]
